framework:
    secret: '%env(APP_SECRET)%'

json_rpc_http_server:
    methods_mapping:
        mappedMethodA:
            service: '@jsonrpc.method.a'
            aliases: 'mappedMethodAAlias'
        mappedMethodB: '@jsonrpc.method.b'
        mappedGetDummy: '@jsonrpc.method.c'
        mappedGetAnotherDummy: '@jsonrpc.method.d'
