# Configure your resolver and add the required tag
services:
  jsonrpc.custom_method_resolver:
    class: Tests\Common\Infra\Symfony\DependencyInjection\CustomMethodResolverClass
    tags: ['yoanm.jsonrpc_http_server.method_resolver']

    # Inject your JSON-RPC methods (They cannot be automatically injected as resolver implementation is on your own)
    calls:
      - method: 'addMethod'
        arguments:
            - '@jsonrpc.method.a'
            - 'custom_methodA'
      - method: 'addMethod'
        arguments:
            - '@jsonrpc.method.b'
            - 'custom_methodB'
      - method: 'addMethod'
        arguments:
            - '@jsonrpc.method.c'
            - 'custom_methodC'
      - method: 'addMethod'
        arguments:
            - '@jsonrpc.method.d'
            - 'custom_methodD'

