# Configure JSON-RPC method services. /!\ Do not forget to define public visibility /!\
services:
  _defaults:
    public: true

  ## JSON-RPC methos
  jsonrpc.method.a:
    class: DemoApp\Method\MethodA
  jsonrpc.method.b:
    class: DemoApp\Method\MethodB
  jsonrpc.method.c:
    class: DemoApp\Method\MethodC
  jsonrpc.method.d:
    class: DemoApp\Method\MethodD


  ## Resolver mock
  resolver:
    class: DemoApp\Resolver\JsonRpcMethodResolver
    calls:
      - ['addMethod', ['@jsonrpc.method.a', 'bundledMethodA']]
      - ['addMethod', ['@jsonrpc.method.a', 'bundledMethodAAlias']]
      - ['addMethod', ['@jsonrpc.method.b', 'bundledMethodB']]
      - ['addMethod', ['@jsonrpc.method.c', 'bundledGetDummy']]
      - ['addMethod', ['@jsonrpc.method.d', 'bundledGetAnotherDummy']]

  # Alias resolver mock to bundle resolver
  json_rpc_http_server.alias.method_resolver: '@resolver'
