# Configure JSON-RPC method services. /!\ Do not forget to define public visibility /!\
services:
  # Configure Json-RPC method MethodA by adding the tag
  jsonrpc.method.a:
    class: DemoApp\Method\MethodA
    public: true
    tags:
      - { name: 'yoanm.jsonrpc_http_server.jsonrpc_method', method: 'defaultMethodA' }
      - { name: 'yoanm.jsonrpc_http_server.jsonrpc_method', method: 'defaultMethodAAlias' }
  # Configure Json-RPC method MethodB with tag also
  jsonrpc.method.b:
    class: DemoApp\Method\MethodB
    public: true
    tags:
        - { name: 'yoanm.jsonrpc_http_server.jsonrpc_method', method: 'defaultMethodB' }

  # Configure Json-RPC method MethodC as simple service, it will be injected on container building
  jsonrpc.method.c:
    class: DemoApp\Method\MethodC
    public: true
  # Configure Json-RPC method MethodD as simple service, it will be injected on container building
  jsonrpc.method.d:
    class: DemoApp\Method\MethodD
    public: true
