# Configure JSON-RPC method services.
services:
  jsonrpc.method.a:
    class: DemoApp\Method\MethodA
    tags:
    - { name: 'json_rpc_http_server.jsonrpc_method', method: 'bundledMethodA' }
    - { name: 'json_rpc_http_server.jsonrpc_method', method: 'bundledMethodAAlias' }
  jsonrpc.method.b:
    class: DemoApp\Method\MethodB
    tags:
    - { name: 'json_rpc_http_server.jsonrpc_method', method: 'bundledMethodB' }
  jsonrpc.method.c:
    class: DemoApp\Method\MethodC
    tags:
    - { name: 'json_rpc_http_server.jsonrpc_method', method: 'bundledGetDummy' }
  jsonrpc.method.d:
    class: DemoApp\Method\MethodD
    tags:
    - { name: 'json_rpc_http_server.jsonrpc_method', method: 'bundledGetAnotherDummy' }

  ## Resolver mock
  resolver:
    class: DemoApp\Resolver\JsonRpcMethodResolver
    tags: ['json_rpc_http_server.method_aware']

  ## Mapping aware service (alias to the resolver)
  mapping_aware_service: '@resolver'

  # Alias resolver mock to bundle resolver
  json_rpc_http_server.alias.method_resolver: '@resolver'
