framework:
    secret: '%env(APP_SECRET)%'

json_rpc_http_server:
    http_endpoint_path: '/my-custom-endpoint'
    methods_mapping:
        bundledMethodA:
            service: '@jsonrpc.method.a'
            aliases: 'bundledMethodAAlias'
        bundledMethodB: '@jsonrpc.method.b'
        bundledGetDummy: '@jsonrpc.method.c'
        bundledGetAnotherDummy: '@jsonrpc.method.d'
