name: 'CI - ComposerRequireChecker'
on:
  workflow_dispatch: # Allows to run the workflow manually from the Actions tab
  workflow_run:
    workflows: ["CI"]
    types:
      - requested

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  # Cache params
  CACHE_VERSION: 2022061906 # To be able to create a new cache (YYYYMMDDXX)
  PHP_VERSION: '8.1' # Latest supported

jobs:
  check:
    name: ComposerRequireChecker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP ${{ env.PHP_VERSION }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: composer
          coverage: none
        env:
          # Always use latest available patch for the version
          update: true

      - name: Setup cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.composer
          # Clear the cache if composer json (as composer.lock is in the repo) has been updated
          key: ${{ env.CACHE_VERSION }}-tests-${{ env.PHP_VERSION }}-${{ hashFiles('composer.json') }}

      - name: Build
        run: make build

      - name: ComposerRequireChecker
        uses: docker://webfactory/composer-require-checker:3.2.0
