name: 'CI - Dependencies check'
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - requested

concurrency:
  group: "CI-${{ github.head_ref }}"
  cancel-in-progress: true

env:
  # Cache params
  CACHE_VERSION: 2022061906 # To be able to create a new cache (YYYYMMDDXX)

jobs:
  check:
    name: Dependencies check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '8.1' # Latest supported
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          coverage: none
        env:
          # Always use latest available patch for the version
          update: true

      - name: Setup cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.composer
          # Clear the cache if composer json (as composer.lock is in the repo) has been updated
          key: ${{ env.CACHE_VERSION }}-tests-${{ matrix.php-version }}-${{ hashFiles('composer.json') }}

      - name: Build
        run: make build

      - name: Dependencies check
        uses: actions/dependency-review-action@v1
