name: 'Nightly'
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  contents: read
  checks: write # For the check run creation !

jobs:
  tests:
    name: Tests
    permissions:
      contents: read
      checks: write # For the check run creation !
    uses: ./.github/workflows/reusable-nightly-tests-workflow.yml
